name: Crowdin Action

on: workflow_dispatch

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: crowdin action
        uses: crowdin/github-action@1.5.1
        with:
          upload_sources: true
          download_translations: true
          push_translations: true
          commit_message: 'New Crowdin translations by Github Action'
          localization_branch_name: l10n_crowdin_action
          create_pull_request: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
